### PR TITLE
Bloxa V0.2

### PR DESCRIPTION
**Pull request by j3qq4hch**
- Current shunts replaced (5 mOhms replaced with 10 mOhms)
- Overcurrent protection added. Itrip is ~35 A
- RCPWM th connector replaced with smd solder pads
- Some design notes added to the schematic

### CODE REVIEW

**Review by pavel-kirienko — CHANGES_REQUESTED** [review]
Please add the internal design documentation per the doc policy. Design objectives, requirements, constraints, etc. as we discussed.

**Comment by pavel-kirienko** [comment]
Also, make sure to remove all links to Autodesk. If you want to add a 3D model, add a separate file.

**Comment by j3qq4hch** [comment]
Все изменения, которые я хочу слить, описаны на этой странице выше. 
То, о чем вы говорите, находится с соседнем пулл-реквесте.

**Review by pavel-kirienko — APPROVED** [review]

**Review by pavel-kirienko — CHANGES_REQUESTED** [review]
Please rebase to master (or merge master in here) and update the README accordingly.

**Comment by j3qq4hch** [comment]
> Please rebase to master (or merge master in here) and update the README accordingly.

Я не понимаю, о чем вы

**Comment by pavel-kirienko** [comment]
Either rebase your branch to master or merge master in it, then update the README to make sure the description is up to date with your latest changes.

**Pull request closed without merging**
